Category.destroy_all
Test.destroy_all
Question.destroy_all
Answer.destroy_all
TestPassage.destroy_all
categories = Category.create([{ title: 'Ruby' }, { title: 'Ruby on Rails' }, { title: 'Javascript' }])
tests = Test.create([{ title: 'Основы Руби', author: User.find_by(email: 'admin@test.guru'),
                       category: categories[0] },
                     { title: 'Мастер Руби', author: User.find_by(email: 'admin@test.guru'),
                       category: categories[0] },
                     { title: 'Rails-модели', level: 4, author: User.find_by(email: 'admin@test.guru'),
                       category: categories[1] },
                     { title: 'Rails-контроллеры', level: 4, author: User.find_by(email: 'admin@test.guru'),
                       category: categories[1] },
                     { title: 'Javascript', level: 2, author: User.find_by(email: 'admin@test.guru'),
                       category: categories[2] }])
questions = Question.create([{ body: 'Как вычисляется квадратный корень?',
                               test: tests[0] },
                             { body: 'Какая команда генерирует модель?',
                               test: tests[2] },
                             { body: 'Как добавить новый элемент в массив?',
                               test: tests[0] },
                             { body: 'Что из перечисленного является коллбеком модели?',
                               test: tests[2] },
                             { body: 'Выберите верный вариант отображение интерполяции строки?',
                               test: tests[1] },
                             { body: 'Краткая запись обьекта proc?',
                               test: tests[1] },
                             { body: 'Что из перечисленного является колбэком контроллера?',
                               test: tests[3] },
                             { body: 'Укажите верный способ,
                               с помощью которого можно обратиться к параметру запроса?',
                               test: tests[3] },
                             { body: 'Что означает выражение "let var = ..."',
                               test: tests[4] }])
Answer.create([{ body: 'Math.sqrt', correct: true, question: questions[0] },
               { body: 'Sqrt.math', correct: false, question: questions[0] },
               { body: 'bin/rails g migration', correct: false, question: questions[1] },
               { body: 'bin/rails g modulation', correct: false, question: questions[1] },
               { body: 'bin/rails g mutation', correct: false, question: questions[1] },
               { body: 'bin/rails g model', correct: true, question: questions[1] },
               { body: 'array.push()', correct: true, question: questions[2] },
               { body: 'array << something', correct: true, question: questions[2] },
               { body: 'array <> something', correct: false, question: questions[2] },
               { body: 'before_validation', correct: true, question: questions[3] },
               { body: 'before congratulations', correct: false, question: questions[3] },
               { body: 'after kill', correct: false, question: questions[3] },
               { body: 'after_commit', correct: true, question: questions[3] },
               { body: '#{}', correct: true, question: questions[4] },
               { body: '{##', correct: false, question: questions[4] },
               { body: '(&..)', correct: true, question: questions[5] },
               { body: '[&...]', correct: false, question: questions[5] },
               { body: '#{&...}#', correct: false, question: questions[5] },
               { body: '--=', correct: false, question: questions[5] },
               { body: 'before_action', correct: true, question: questions[6] },
               { body: 'before_satisfaction', correct: false, question: questions[6] },
               { body: 'after_satisfaction', correct: false, question: questions[6] },
               { body: 'params[:id]', correct: true, question: questions[7] },
               { body: 'pararams[:id]', correct: false, question: questions[7] },
               { body: '{id:}', correct: false, question: questions[8] },
               { body: 'парамс', correct: false, question: questions[8] },
               { body: 'Назначение переменной', correct: true, question: questions[9] },
               { body: 'Нечто большее и глобальное', correct: false, question: questions[9] }])
